"""
Mock zCloud API Package
提供zCloud平台的Mock API，用于开发和测试
"""
from mock_zcloud_api.models import (
    # 基础模型
    Instance,
    Alert,
    Session,
    LockInfo,
    SlowSQL,
    TopSQL,
    SQLPlan,
    ReplicationInfo,
    Parameter,
    DiskUsage,
    CapacityInfo,
    HAStatus,
    InspectionTask,
    WorkOrder,
    WorkOrderCreate,
    ConfigDeviation,
    # 基础生成器
    gen_instance,
    gen_alerts,
    gen_sessions,
    gen_locks,
    gen_slow_sqls,
    gen_top_sqls,
    gen_replication,
    gen_parameters,
    gen_disk_usage,
    gen_ha_status,
    gen_inspection_result,
    gen_workorder,
    gen_config_deviation,
)
from mock_zcloud_api.models_enhanced import (
    # 增强模型
    EnhancedAlert,
    EnhancedInstance,
    EnhancedSession,
    EnhancedLock,
    EnhancedSlowSQL,
    EnhancedTablespace,
    EnhancedWorkOrder,
    AlertAnnotation,
    AlertCustomFields,
    NestedAlert,
    SQLPlanStep,
    # 增强生成器
    gen_enhanced_alert,
    gen_enhanced_instance,
    gen_enhanced_sessions,
    gen_enhanced_locks,
    gen_enhanced_slow_sqls,
    gen_sql_plan,
    gen_enhanced_tablespaces,
    gen_enhanced_workorder,
)

__all__ = [
    # 基础模型
    "Instance",
    "Alert",
    "Session",
    "LockInfo",
    "SlowSQL",
    "TopSQL",
    "SQLPlan",
    "ReplicationInfo",
    "Parameter",
    "DiskUsage",
    "CapacityInfo",
    "HAStatus",
    "InspectionTask",
    "WorkOrder",
    "WorkOrderCreate",
    "ConfigDeviation",
    # 基础生成器
    "gen_instance",
    "gen_alerts",
    "gen_sessions",
    "gen_locks",
    "gen_slow_sqls",
    "gen_top_sqls",
    "gen_replication",
    "gen_parameters",
    "gen_disk_usage",
    "gen_ha_status",
    "gen_inspection_result",
    "gen_workorder",
    "gen_config_deviation",
    # 增强模型
    "EnhancedAlert",
    "EnhancedInstance",
    "EnhancedSession",
    "EnhancedLock",
    "EnhancedSlowSQL",
    "EnhancedTablespace",
    "EnhancedWorkOrder",
    "AlertAnnotation",
    "AlertCustomFields",
    "NestedAlert",
    "SQLPlanStep",
    # 增强生成器
    "gen_enhanced_alert",
    "gen_enhanced_instance",
    "gen_enhanced_sessions",
    "gen_enhanced_locks",
    "gen_enhanced_slow_sqls",
    "gen_sql_plan",
    "gen_enhanced_tablespaces",
    "gen_enhanced_workorder",
]
